services:
  db:
    image: mongo
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: store
